export const HEALTH_DAYS = [
  // Official WHO & UN Health/Science Days
  { name: 'World Neglected Tropical Diseases Day', month: 0, day: 30, keywords: ['NTD', 'tropical disease', 'dengue', 'leprosy'] },
  { name: 'World Cancer Day', month: 1, day: 4, keywords: ['cancer', 'oncology', 'chemotherapy', 'tumor'] },
  { name: 'International Day of Women and Girls in Science', month: 1, day: 11, keywords: ['women in science', 'stem', 'female scientists'] },
  { name: 'World Hearing Day', month: 2, day: 3, keywords: ['hearing', 'deafness', 'ear health'] },
  { name: 'World Down Syndrome Day', month: 2, day: 21, keywords: ['down syndrome', 'trisomy 21'] },
  { name: 'World TB Day', month: 2, day: 24, keywords: ['tuberculosis', 'tb', 'lung health'] },
  { name: 'World Autism Awareness Day', month: 3, day: 2, keywords: ['autism', 'asd', 'neurodiversity'] },
  { name: 'World Health Day', month: 3, day: 7, keywords: ['who', 'public health', 'global health'] },
  { name: 'World Chagas Disease Day', month: 3, day: 14, keywords: ['chagas', 'silent disease'] },
  { name: 'World Malaria Day', month: 3, day: 25, keywords: ['malaria', 'mosquito', 'plasmodium'] },
  { name: 'World Hand Hygiene Day', month: 4, day: 5, keywords: ['hand hygiene', 'infection control', 'wash hands'] },
  { name: 'World Obstetric Fistula Day', month: 4, day: 23, keywords: ['fistula', 'maternal health', 'obstetric'] },
  { name: 'World No Tobacco Day', month: 4, day: 31, keywords: ['tobacco', 'smoking', 'vaping', 'nicotine'] },
  { name: 'World Food Safety Day', month: 5, day: 7, keywords: ['food safety', 'foodborne', 'nutrition'] },
  { name: 'World Blood Donor Day', month: 5, day: 14, keywords: ['blood donor', 'blood transfusion', 'donate blood'] },
  { name: 'World Drowning Prevention Day', month: 6, day: 25, keywords: ['drowning', 'water safety'] },
  { name: 'World Hepatitis Day', month: 6, day: 28, keywords: ['hepatitis', 'liver health', 'hepc', 'hepb'] },
  { name: 'World Patient Safety Day', month: 8, day: 17, keywords: ['patient safety', 'healthcare quality'] },
  { name: 'World Rabies Day', month: 8, day: 28, keywords: ['rabies', 'vaccination', 'zoonotic'] },
  { name: 'World Mental Health Day', month: 9, day: 10, keywords: ['mental health', 'depression', 'anxiety', 'psychiatry'] },
  { name: 'World Diabetes Day', month: 10, day: 14, keywords: ['diabetes', 'insulin', 'blood sugar'] },
  { name: 'World Prematurity Day', month: 10, day: 15, keywords: ['prematurity', 'preterm', 'neonatal'] },
  { name: 'World Cervical Cancer Elimination Day', month: 10, day: 17, keywords: ['cervical cancer', 'hpv', 'pap smear'] },
  { name: 'World AIDS Day', month: 11, day: 1, keywords: ['aids', 'hiv', 'antiretroviral'] },
  { name: 'Universal Health Coverage Day', month: 11, day: 12, keywords: ['uhc', 'health for all', 'healthcare access'] }
];
